services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        app_mode: ${APP_MODE}
    image: php:8.3.7-fpm-alpine3.19
    container_name: ${PROJECT_NAME}
    volumes:
      - app_data:/var/www/html
      - ./src/index.php:/var/www/html/public/index.php
    networks:
      - network
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        app_type: ${APP_TYPE}
    ports:
      - 3000:80
      - 3001:443
    image: nginx:1.26.0-alpine3.19-slim
    networks:
      - network
    depends_on:
      - app

  db:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: intmap
      MYSQL_PASSWORD: intmap
    ports:
      - 3002:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network

networks:
  network:
    name: ${PROJECT_NAME}
volumes:
  app_data:
  db_data:
